### ISSUE TITLE
Huawei MA5608T SNMP: VLAN-to-interface associations cannot be resolved from the available port identifiers

### ISSUE THREAD

**Issue by ssgadzhi** [netboxlabs/orb-agent#631]
## Summary

Following the VLAN catalog fix confirmed in #624, we collected the three requested SNMP walks from the same physical Huawei MA5608T.

The device exposes per-VLAN membership through `hwVlanPorts`, but it does not expose the standard `dot1dBasePortTable` needed to translate bridge-port positions to interface indexes. The available `ifDescr` values are also not unique for the physical ports.

As a result, SNMP discovery emits all 13 VLANs but no interface `mode`, `tagged_vlans`, or `untagged_vlan` associations.

## Environment

- Device: Huawei SmartAX MA5608T
- sysObjectID: `.1.3.6.1.4.1.2011.2.248`
- Orb Agent: `2.14.0-07af109` (develop)
- SNMP Discovery: `1.36.1`
- Protocol: SNMPv2c
- Mode: dry-run
- Related VLAN catalog issue: #624

## Discovery result

The dry-run contains:

```text
device:      1
interface:  23
ip_address:  8
prefix:      7
vlan:       13
```

All 13 expected VLANs are present, confirming the catalog fix from #624.

However, no interface entity contains any of these fields:

```text
mode
tagged_vlans
untagged_vlan
```

### Standard bridge-port mapping

A complete walk of `dot1dBasePortTable` returns:

```text
.1.3.6.1.2.1.17.1.4 = No Such Object available on this agent at this OID
```

Therefore, the standard bridge-port-to-ifIndex mapping is unavailable.

### Huawei VLAN membership

`hwVlanPorts` is available at:

```text
.1.3.6.1.4.1.2011.5.6.1.1.1.3
```

It returns one long hexadecimal string for each of the 13 VLAN IDs. The values differ between VLANs, confirming that the device exposes VLAN membership information through this table.

Observed rows include VLAN IDs:

```text
1, 50, 158, 159, 632, 634, 647, 664, 682, 683, 684, 685, 941
```

### Interface descriptions

`ifDescr` is available, but its physical-port values are not unique:

```text
4 entries:  Huawei-MA5600-V800R018-ETHERNET
16 entries: Huawei-MA5600-V800R018-GPON_UNI
1 entry:    Huawei-MA5600-V800R018-BITS
```

The remaining entries identify logical interfaces such as loopbacks, the management interface, and VLAN interfaces.

Each repeated physical description has a different ifIndex, but the emitted dry-run interface names use these repeated descriptions. This leaves multiple interface entities on the same device with identical names.

## Conclusion

The requested walks confirm that:

1. VLAN membership information exists in `hwVlanPorts`.
2. The standard `dot1dBasePortTable` mapping is absent.
3. `ifDescr` alone cannot uniquely identify the physical ports.

We agree that the `hwVlanPorts` bitmap should not be mapped to interfaces by assumption.

Could you identify the Huawei-specific table needed to translate the bitmap positions or physical port identifiers to stable interface indexes and names on the MA5608T?

We have retained the complete outputs of all three walks locally and can provide sanitized captures if they are needed.

**Comment by samiura** [comment]
@ssgadzhi thank you for opening this follow up issue, we will update you shortly on this one.

**Comment by samiura** [comment]
@ssgadzhi thanks for the walks — they line up with what we found on our side, and the picture is encouraging.

The hwVlanPorts encoding is documented in HUAWEI-VLAN-MIB: 8 octets per slot, 64 ports per slot, so bit position = slot × 64 + port. And the slot/port → interface link is available even without dot1dBasePortTable: on this platform ifName is unique and carries frame/slot/port (e.g. ethernet0/7/0, GPON 0/0/0), unlike ifDescr. That should also explain the duplicate interface names you noticed — as a workaround today, set options.interface_name_source: ifname in the policy and the interfaces will be named from ifName.

What hwVlanPorts does not carry is tagged vs untagged. To confirm the bit ordering and see whether the device exposes PVID/port-type, could you share:

snmpwalk -v2c -c <community> <host> .1.3.6.1.2.1.31.1.1.1.1              # ifName
snmpwalk -v2c -c <community> <host> .1.3.6.1.4.1.2011.5.25.42.1.1.1.3    # HUAWEI-L2IF-MIB hwL2IfTable (PVID / port type), if implemented
snmpwalk -v2c -c <community> <host> .1.3.6.1.4.1.2011.5.6.1.1.1.3.682    # hwVlanPorts for VLAN 682, raw hex
snmpwalk -v2c -c <community> <host> .1.3.6.1.4.1.2011.5.6.1.1.1.3.50     # hwVlanPorts for VLAN 50, raw hex

**Comment by ssgadzhi** [comment]
Hi @samiura,

Here are the four requested walks from the same physical MA5608T.

`ifName` is available and unique. The requested `hwL2IfTable` subtree is not implemented. VLAN 682 has a non-zero `hwVlanPorts` value, while VLAN 50 has an all-zero value.

<details>
<summary>Complete SNMP output</summary>

```text
.1.3.6.1.2.1.31.1.1.1.1.128 = STRING: "InLoopBack0"
.1.3.6.1.2.1.31.1.1.1.1.262 = STRING: "null0"
.1.3.6.1.2.1.31.1.1.1.1.263 = STRING: "meth0"
.1.3.6.1.2.1.31.1.1.1.1.264 = STRING: "vlanif50"
.1.3.6.1.2.1.31.1.1.1.1.265 = STRING: "vlanif682"
.1.3.6.1.2.1.31.1.1.1.1.266 = STRING: "vlanif683"
.1.3.6.1.2.1.31.1.1.1.1.267 = STRING: "vlanif684"
.1.3.6.1.2.1.31.1.1.1.1.268 = STRING: "vlanif685"
.1.3.6.1.2.1.31.1.1.1.1.269 = STRING: "loopback0"
.1.3.6.1.2.1.31.1.1.1.1.234897408 = STRING: "ethernet0/2/0"
.1.3.6.1.2.1.31.1.1.1.1.234897472 = STRING: "ethernet0/2/1"
.1.3.6.1.2.1.31.1.1.1.1.234897536 = STRING: "ethernet0/2/2"
.1.3.6.1.2.1.31.1.1.1.1.234897600 = STRING: "ethernet0/2/3"
.1.3.6.1.2.1.31.1.1.1.1.3221242112 = STRING: "bits0/2/4"
.1.3.6.1.2.1.31.1.1.1.1.4194304000 = STRING: "GPON 0/0/0"
.1.3.6.1.2.1.31.1.1.1.1.4194304256 = STRING: "GPON 0/0/1"
.1.3.6.1.2.1.31.1.1.1.1.4194304512 = STRING: "GPON 0/0/2"
.1.3.6.1.2.1.31.1.1.1.1.4194304768 = STRING: "GPON 0/0/3"
.1.3.6.1.2.1.31.1.1.1.1.4194305024 = STRING: "GPON 0/0/4"
.1.3.6.1.2.1.31.1.1.1.1.4194305280 = STRING: "GPON 0/0/5"
.1.3.6.1.2.1.31.1.1.1.1.4194305536 = STRING: "GPON 0/0/6"
.1.3.6.1.2.1.31.1.1.1.1.4194305792 = STRING: "GPON 0/0/7"
.1.3.6.1.2.1.31.1.1.1.1.4194306048 = STRING: "GPON 0/0/8"
.1.3.6.1.2.1.31.1.1.1.1.4194306304 = STRING: "GPON 0/0/9"
.1.3.6.1.2.1.31.1.1.1.1.4194306560 = STRING: "GPON 0/0/10"
.1.3.6.1.2.1.31.1.1.1.1.4194306816 = STRING: "GPON 0/0/11"
.1.3.6.1.2.1.31.1.1.1.1.4194307072 = STRING: "GPON 0/0/12"
.1.3.6.1.2.1.31.1.1.1.1.4194307328 = STRING: "GPON 0/0/13"
.1.3.6.1.2.1.31.1.1.1.1.4194307584 = STRING: "GPON 0/0/14"
.1.3.6.1.2.1.31.1.1.1.1.4194307840 = STRING: "GPON 0/0/15"

.1.3.6.1.4.1.2011.5.25.42.1.1.1.3 = No Such Object available on this agent at this OID

.1.3.6.1.4.1.2011.5.6.1.1.1.3.682 = Hex-STRING:
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 43 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30

.1.3.6.1.4.1.2011.5.6.1.1.1.3.50 = Hex-STRING:
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
```

</details>

**Comment by samiura** [comment]
Hi @ssgadzhi  — the fix for this is merged to develop and in the netboxlabs/orb-agent:develop image (2.14.0-ebe6ee1). Could you run it against the MA5608T and let us know how it looks?

What it does: reads hwVlanPorts from HUAWEI-VLAN-MIB, decodes the bitmap using the MIB's slot/port layout, and maps the bits to interfaces via ifName (e.g. ethernet0/2/2). Interfaces carrying VLANs should now show mode: tagged with the VIDs in tagged_vlans. Setting options.interface_name_source: ifname in the policy is recommended since ifDescr isn't unique on this device.

Two things that would help us: (1) confirm the tagged ports per VLAN match display vlan <vid> on the OLT, and (2) let us know if any VLAN shows no ports or the wrong ones — if so, please share the ifName values and the raw hwVlanPorts for that VLAN.

Not covered: untagged_vlan/PVID (the device doesn't implement hwL2IfTable) and GPON service-port VLANs. We'll keep this open until the fix ships in a tagged release.

**Comment by ssgadzhi** [comment]
Hi @samiura,

Confirmed on the physical MA5608T using `develop 2.14.0-ebe6ee1`.

The policy was run with:

```yaml
options:
  interface_name_source: ifname
```

The dry-run retained the expected catalog and entity counts:

- 1 device
- 23 interfaces
- 8 IP addresses
- 7 prefixes
- 13 VLANs

Four physical Ethernet interfaces now contain VLAN fields and use their unique `ifName` values:

```text
ethernet0/2/0
ethernet0/2/1
ethernet0/2/2
ethernet0/2/3
```

We compared the decoded associations with `display vlan <vid>` on the OLT.

### VLAN 682

Orb:

```text
ethernet0/2/2
ethernet0/2/3
```

OLT CLI:

```text
F/S/P 0/2/2
F/S/P 0/2/3
Standard port number: 2
```

The result matches exactly.

### VLAN 158

Orb:

```text
ethernet0/2/2
ethernet0/2/3
```

OLT CLI:

```text
F/S/P 0/2/2
F/S/P 0/2/3
Standard port number: 2
```

The result matches exactly.

### VLAN 1

Orb:

```text
ethernet0/2/0
ethernet0/2/1
ethernet0/2/2
ethernet0/2/3
```

OLT CLI reports the same four standard ports:

```text
F/S/P 0/2/0
F/S/P 0/2/1
F/S/P 0/2/2
F/S/P 0/2/3
Standard port number: 4
```

Two ports are currently down, but their configured VLAN membership is still correctly retained.

### VLAN 50

Orb emits no physical Ethernet association for VLAN 50.

The OLT CLI confirms:

```text
Standard port number: 0
```

The CLI also reports GPON service virtual ports for VLAN 50. These are not represented by the physical Ethernet membership bitmap and are outside the stated scope of this implementation, so their absence from the Orb interface associations is expected.

All discovered standard-port memberships checked against the CLI are correct.

As expected, the output contains no `untagged_vlan`: the device does not implement the requested `hwL2IfTable`, so PVID/native-VLAN classification is not available. The current result therefore represents the discovered memberships as tagged, in accordance with the documented scope of the fix.

This confirms the Huawei standard-port VLAN membership decoding and interface mapping on our physical MA5608T. Thank you!

**Comment by samiura** [comment]
Hi @ssgadzhi — the fix for this is merged to develop and in the `netboxlabs/orb-agent:develop` image (`2.14.0-ebe6ee1`). Could you run it against the MA5608T and let us know how it looks?

What it does: reads `hwVlanPorts` from HUAWEI-VLAN-MIB, decodes the bitmap using the MIB's slot/port layout, and maps the bits to interfaces via ifName (e.g. ethernet0/2/2). Interfaces carrying VLANs should now show mode: tagged with the VIDs in tagged_vlans. Setting options.interface_name_source: ifname in the policy is recommended since ifDescr isn't unique on this device.

Two things that would help us: 

 1. Confirm the tagged ports per VLAN match display vlan <vid> on the OLT
 2. Let us know if any VLAN shows no ports or the wrong ones — if so, please share the ifName values and the raw hwVlanPorts for that VLAN.

**Not covered:** untagged_vlan/PVID (the device doesn't implement hwL2IfTable) and GPON service-port VLANs.

**Comment by ssgadzhi** [comment]
Hi @samiura,

This was already validated against the physical MA5608T in our earlier comment, and we have now repeated the test using the tagged `orb-agent 2.15.0` release with SNMP Discovery `1.37.0`.

The result remains correct:

- 1 device
- 23 interfaces
- 8 IP addresses
- 7 prefixes
- 13 VLANs

The policy uses:

```yaml
options:
  interface_name_source: ifname
```

The discovered standard-port memberships are:

```text
VLAN 1:
  ethernet0/2/0
  ethernet0/2/1
  ethernet0/2/2
  ethernet0/2/3

VLAN 158:
  ethernet0/2/2
  ethernet0/2/3

VLAN 682:
  ethernet0/2/2
  ethernet0/2/3
```

These associations match the corresponding `display vlan <vid>` output on the OLT exactly.

VLAN 50 has no physical Ethernet association in Orb, and the OLT reports `Standard port number: 0`, so this is also correct. Its GPON service virtual ports are outside the scope of the physical Ethernet membership bitmap.

We did not find any VLAN with an incorrect standard-port association. As expected, `untagged_vlan`/PVID is not populated because this MA5608T does not implement the required `hwL2IfTable`.

Therefore, the Huawei standard-port VLAN membership decoding and `ifName` mapping are confirmed working on the tagged `2.15.0` release. From our side, this issue can be closed.

Previous detailed validation: https://github.com/netboxlabs/orb-agent/issues/631#issuecomment-5694435586

**Comment by leoparente** [comment]
Fix present in orb-agent [v2.15.0](https://github.com/netboxlabs/orb-agent/releases/tag/v2.15.0)
